name: Continuous Integration

on: [push]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - uses: actions/setup-java@v5.0.0
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'

    - run: gradle publishToMavenLocal check
